### ISSUE TITLE
Update to support v8 and deno deploy

### ISSUE THREAD

**Issue by spendres** [maximousblk/passkeys-demo#1]
Updates to consider:
1. Making relying party id configurable is required to host the solution on any domain other than localhost
2. Updating to SimpleWebAuthn v8+ allows directly importing from deno.land using esm imports.

To work on deno deploy, this example must at the minimum import npm version v8+ or switch to deno.land/x/SimpleWebAuthn import. In version 8+ , the two getAuthenticatorOptions and getRegistrationOptions functions will need an await as they were changed to async.

**Comment by maximousblk** [comment]
Take a look at https://passkeys.deno.dev/ and let me know if it looks good.

**Comment by spendres** [comment]
Looks excellent. Thank you, for updating and deploying.

I was able to register on iPhone13 using iOS15.5.1 then login through
Safari 16.5.1 on macbook pro seamlessly. I also used Chrome 17.0.5938.88
that prompted for auth through the 2D barcode, which worked.
I have NOT tried Chrome 18beta, but would expect that to work as seamlessly
as Safari.

Consider submitting this to the Deno team as an approximation for a
Passkey/KV plugin for fresh, hono, and oak.

**Comment by spendres** [comment]
The phrase "Passkeys are supported" may be more clear directed at the user
as "Your system supports Passkeys"... since passkeys.deno.dev clearly
supports passkeys.
Also:
"login" button would be clearer as "use passkey" since you support
anonymous.
"register" button would be clearer as "new passkey"
Consider using the passkey finger-print-icon next to the buttons.

FYI: I could not get a Yubikey 5 Series to register.
